# Generated by Django 5.1.3 on 2024-11-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['body_type'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gearbox', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(default=models.CharField(max_length=50), max_length=100)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('priority', models.IntegerField(default=0)),
                ('price', models.CharField(max_length=50)),
                ('horsepower', models.CharField(max_length=10)),
                ('torque', models.CharField(max_length=50)),
                ('fuel', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('hybrid', 'hybrid')], max_length=50)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_style', to='Home.bodytype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_brand', to='Home.brand')),
                ('transmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gearbox_type', to='Home.transmission')),
            ],
        ),
    ]
